"""统一路径、时间范围和实验参数。"""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / 'data'
RAW_DATA_DIR = DATA_DIR / 'raw'
PROCESSED_DATA_DIR = DATA_DIR / 'processed'
MODEL_DIR = ROOT / 'models'
OUTPUT_DIR = ROOT / 'output'
PREDICTION_NO_HEADER_PATH = OUTPUT_DIR / 'prediction_201409_no_header.csv'
EVENT_DISTANCE_CANDIDATE_PATH = OUTPUT_DIR / 'tc_comp_predict_table_event_distance_candidate.csv'
EVENT_DISTANCE_PURCHASE_ONLY_PATH = OUTPUT_DIR / 'tc_comp_predict_table_event_purchase_only.csv'
EVENT_DISTANCE_REDEEM_ONLY_PATH = OUTPUT_DIR / 'tc_comp_predict_table_event_redeem_only.csv'
EVENT_DISTANCE_MANIFEST_PATH = OUTPUT_DIR / 'event_distance_manifest.json'
C3_BACKTEST_PRED_PATH = OUTPUT_DIR / 'rolling_backtest_predictions.csv'
C3_BACKTEST_METRICS_PATH = OUTPUT_DIR / 'rolling_backtest_metrics.csv'
C3_CALENDAR_CANDIDATE_PATH = OUTPUT_DIR / 'tc_comp_predict_table_calendar_candidate.csv'
C3_CALENDAR_METRICS_PATH = OUTPUT_DIR / 'calendar_forecast_metrics.csv'
C3_MONTHLY_SHAPE_CANDIDATE_PATH = OUTPUT_DIR / 'tc_comp_predict_table_monthly_shape_candidate.csv'
C3_MONTHLY_SHAPE_METRICS_PATH = OUTPUT_DIR / 'monthly_shape_metrics.csv'
C3_EVENT_DISTANCE_METRICS_PATH = OUTPUT_DIR / 'event_distance_metrics.csv'
C3_EVENT_DISTANCE_VALIDATION_PATH = OUTPUT_DIR / 'event_distance_validation_predictions.csv'
TRAIN_START, TRAIN_END = '2013-07-01', '2014-08-31'
FORECAST_START, FORECAST_END = '2014-09-01', '2014-09-30'
RANDOM_STATE = 42
LAG_FEATURES = (1, 2, 3, 7, 14, 21, 28, 30)
ROLLING_WINDOWS = (3, 7, 14, 30)
PURCHASE_WEIGHT, REDEEM_WEIGHT = .45, .55
TARGETS = ('purchase', 'redeem')
EPSILON = 1.0  # 原始金额单位；零值另行报告，MAPE 使用这个下限
FOLDS = (('2014-06-01','2014-06-30'), ('2014-07-01','2014-07-31'), ('2014-08-01','2014-08-31'))
